apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: demo-cluster
  namespace: demo
  labels:
    tkg-cluster-selector: demo-cluster
spec:
  topology:
    class: tanzukubernetescluster
    version: v1.30.1---vmware.1-fips-tkg.5
    variables:
      - name: storageClasses
        value:
          - tanzu-storage-policy
      - name: defaultStorageClass
        value: tanzu-storage-policy
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: tanzu-storage-policy
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon
    workers:
      machineDeployments:
        - class: node-pool
          name: demo-cluster-nodepool-f4nq
          replicas: 3
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon
